version: '2'
services:
    partypayback-app:
        image: partypayback
        external_links:
            - partypayback-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/partyPayback
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    partypayback-postgresql:
        extends:
            file: postgresql.yml
            service: partypayback-postgresql
